import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../skills/agent-outsource/scripts/db.mjs';import {cachedModels,refreshModels} from '../skills/agent-outsource/scripts/models.mjs';
const make=()=>new Store(path.join(fs.mkdtempSync(path.join(os.tmpdir(),'model-cache-')),'db.sqlite'));
test('model cache starts empty, refreshes explicitly, preserves successful snapshot on failure',async()=>{
 const s=make();try{assert.equal(cachedModels(s,'antigravity').cached,false);let calls=0;
 const ok=await refreshModels(s,'antigravity',async(exe,args)=>{calls++;assert.deepEqual(args,['models']);return 'Fetching available models...\na\tModel A\nb\tModel B\n'});assert.equal(ok.refreshed,true);assert.equal(ok.models.length,2);
 const snapshot=JSON.stringify(cachedModels(s,'antigravity'));cachedModels(s,'antigravity');assert.equal(calls,1);
 for(const run of [async()=>{throw Error('offline')},async()=>'',async()=>'bad format',async()=>'a\tA\na\tDuplicate']){assert.equal((await refreshModels(s,'antigravity',run)).refreshed,false);assert.equal(JSON.stringify(cachedModels(s,'antigravity')),snapshot);}
 const next=await refreshModels(s,'antigravity',async()=>'c\tModel C');assert.deepEqual(next.models.map(m=>m.id),['c']);
 }finally{s.close();}});
test('Claude refresh uses SDK options and preserves cache on SDK failure',async()=>{const s=make();try{const r=await refreshModels(s,'claude',()=>{throw Error('wrong CLI path')},async()=>[{id:'default',name:'Default'}]);assert.equal(r.refreshed,true);assert.match(r.scope,/not an API catalog/);const saved=JSON.stringify(cachedModels(s,'claude'));const failed=await refreshModels(s,'claude',null,async()=>{throw Error('SDK unavailable')});assert.equal(failed.refreshed,false);assert.equal(JSON.stringify(cachedModels(s,'claude')),saved);}finally{s.close();}});

test('failed replacement transaction rolls back models and timestamp',async()=>{const s=make();try{await refreshModels(s,'antigravity',async()=>'old\tOld');const before=JSON.stringify(cachedModels(s,'antigravity'));s.db.exec("CREATE TRIGGER reject_new BEFORE INSERT ON models WHEN NEW.model_id='new' BEGIN SELECT RAISE(ABORT,'fixture rejection'); END");assert.equal((await refreshModels(s,'antigravity',async()=>'new\tNew')).refreshed,false);assert.equal(JSON.stringify(cachedModels(s,'antigravity')),before);}finally{s.close();}});
test('schema migration retains existing job and model rows on reopen',()=>{const s=make(),file=s.filename;try{s.db.exec('PRAGMA user_version=1');s.run('INSERT INTO models VALUES(?,?,?)','antigravity','keep','Keep');s.run('INSERT INTO controls VALUES(?,?)','fixture','preserve');}finally{s.close();}const reopened=new Store(file);try{assert.equal(reopened.get('PRAGMA user_version').user_version,2);assert.equal(reopened.get('SELECT value FROM controls').value,'preserve');assert.equal(cachedModels(reopened,'antigravity').models[0].id,'keep');}finally{reopened.close();}});

import {queryClaudeModels} from '../skills/agent-outsource/scripts/claude-models.mjs';
test('SDK initialization sends no prompt, uses installed CLI, and closes',async()=>{let closed=false,prompt;const rows=await queryClaudeModels(async()=>({query:input=>{prompt=input.prompt;assert.equal(input.options.persistSession,false);assert.equal(input.options.allowDangerouslySkipPermissions,true);assert.deepEqual(input.options.tools,[]);return {supportedModels:async()=>[{value:'sonnet',displayName:'Sonnet'}],close:()=>{closed=true}}}}));assert.deepEqual(rows,[{id:'sonnet',name:'Sonnet'}]);assert.equal(closed,true);assert.equal((await prompt.next()).done,true);});
test('SDK timeout and malformed response close session without caching',async()=>{for(const data of [[],[{value:'x'}],[{value:'x',displayName:'X'},{value:'x',displayName:'X'}]]){let closed=false;await assert.rejects(queryClaudeModels(async()=>({query:()=>({supportedModels:async()=>data,close:()=>{closed=true}})})));assert.equal(closed,true);}let closed=false;await assert.rejects(queryClaudeModels(async()=>({query:()=>({supportedModels:()=>new Promise(()=>{}),close:()=>{closed=true}})}),10),/timed out/);assert.equal(closed,true);});
