import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {Store} from '../skills/agent-outsource/scripts/db.mjs';import {cachedModels,refreshModels} from '../skills/agent-outsource/scripts/models.mjs';
const make=()=>new Store(path.join(fs.mkdtempSync(path.join(os.tmpdir(),'model-cache-')),'db.sqlite'));
test('model cache starts empty, refreshes explicitly, preserves successful snapshot on failure',async()=>{
 const s=make();try{assert.equal(cachedModels(s,'antigravity').cached,false);let calls=0;
 const ok=await refreshModels(s,'antigravity',async(exe,args)=>{calls++;assert.deepEqual(args,['models']);return 'Fetching available models...\na\tModel A\nb\tModel B\n'});assert.equal(ok.refreshed,true);assert.equal(ok.models.length,2);
 const snapshot=JSON.stringify(cachedModels(s,'antigravity'));cachedModels(s,'antigravity');assert.equal(calls,1);
 for(const run of [async()=>{throw Error('offline')},async()=>'',async()=>'bad format',async()=>'a\tA\na\tDuplicate']){assert.equal((await refreshModels(s,'antigravity',run)).refreshed,false);assert.equal(JSON.stringify(cachedModels(s,'antigravity')),snapshot);}
 const next=await refreshModels(s,'antigravity',async()=>'c\tModel C');assert.deepEqual(next.models.map(m=>m.id),['c']);
 }finally{s.close();}});
test('unsupported Claude refresh preserves cache and never launches a model',async()=>{const s=make();try{s.run('INSERT INTO models VALUES(?,?,?)','claude','saved','Saved');s.run('INSERT INTO model_refresh VALUES(?,?)','claude',123);const r=await refreshModels(s,'claude',()=>{throw Error('must not query')});assert.equal(r.error,'unsupported');assert.equal(r.lastSuccess,123);assert.equal(r.models[0].id,'saved');}finally{s.close();}});
test('failed replacement transaction rolls back models and timestamp',async()=>{const s=make();try{await refreshModels(s,'antigravity',async()=>'old\tOld');const before=JSON.stringify(cachedModels(s,'antigravity'));s.db.exec("CREATE TRIGGER reject_new BEFORE INSERT ON models WHEN NEW.model_id='new' BEGIN SELECT RAISE(ABORT,'fixture rejection'); END");assert.equal((await refreshModels(s,'antigravity',async()=>'new\tNew')).refreshed,false);assert.equal(JSON.stringify(cachedModels(s,'antigravity')),before);}finally{s.close();}});
test('schema migration retains existing job and model rows on reopen',()=>{const s=make(),file=s.filename;try{s.db.exec('PRAGMA user_version=1');s.run('INSERT INTO models VALUES(?,?,?)','antigravity','keep','Keep');s.run('INSERT INTO controls VALUES(?,?)','fixture','preserve');}finally{s.close();}const reopened=new Store(file);try{assert.equal(reopened.get('PRAGMA user_version').user_version,2);assert.equal(reopened.get('SELECT value FROM controls').value,'preserve');assert.equal(cachedModels(reopened,'antigravity').models[0].id,'keep');}finally{reopened.close();}});
